id: 8cbc0bd0-d5dc-49b6-8229-7f8b1744333d
inputs: []
name: Sample Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e5e3bf98-fee9-4676-8c7a-4af3adcc50ed
      iscommand: false
      name: ""
      version: -1
    taskid: e5e3bf98-fee9-4676-8c7a-4af3adcc50ed
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Hello Sample
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 1ea9776d-c8f6-45b5-8cf7-2cc14755e4b5
      iscommand: false
      name: Sample Print
      script: Print
      type: regular
      version: -1
    taskid: 1ea9776d-c8f6-45b5-8cf7-2cc14755e4b5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      af_cookie: {}
      class:
        simple: Campaign
      commodity: {}
      interval_in_seconds: {}
      polling: {}
      private: {}
      public: {}
      scope:
        simple: industry
      unit42: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Performs a search to identify the most popular tags. `Autofocus
        Query Samples, Sessions and Tags` Playbook is recommended for querying and
        polling.
      id: c74f1bc3-d147-4748-8f36-dc9148716aa5
      iscommand: true
      name: Sample AF Enrich
      script: '|||autofocus-top-tags-search'
      type: regular
      version: -1
    taskid: c74f1bc3-d147-4748-8f36-dc9148716aa5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
