id: 7e9871f9-6e74-4a65-82ae-249110c1812b
inputs: []
name: IP Indicator Enrichment - Example
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f6f3c71f-0307-4db4-807c-ca5a34a2dee5
      iscommand: false
      name: ""
      version: -1
    taskid: f6f3c71f-0307-4db4-807c-ca5a34a2dee5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      entryID: {}
      filePath: {}
      investigationID: {}
      text:
        simple: ${incident.details}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.extract.indicators
      id: e495b353-7a28-4227-8d86-a3d1b6a2f878
      iscommand: true
      name: Extract Indicators
      script: Builtin|||extractIndicators
      type: regular
      version: -1
    taskid: e495b353-7a28-4227-8d86-a3d1b6a2f878
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
      - "4"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      value:
        simple: ${ExtractedIndicators.IP}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the overall score for the indicator as calculated by DBot.
      id: 3a183404-3249-420c-8747-9218fddc18c7
      iscommand: false
      name: Check IPs in DBotScore Cache
      script: 63d2601d-b227-4a72-87e6-a739705c6651
      type: regular
      version: -1
    taskid: 3a183404-3249-420c-8747-9218fddc18c7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 370
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e4186cbf-06b3-43aa-8877-e14e62744c95
      iscommand: false
      name: Cache Entry
      type: title
      version: -1
    taskid: e4186cbf-06b3-43aa-8877-e14e62744c95
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ce52f487-68ba-41b8-8147-faf42eb421de
      iscommand: false
      name: Does Not Exist
      type: title
      version: -1
    taskid: ce52f487-68ba-41b8-8147-faf42eb421de
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 500,
          "y": 545
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    reputationcalc: 2
    scriptarguments:
      ip:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: ExtractedIndicators.IP
              operator: notIn
              right:
                iscontext: true
                value:
                  simple: DBotScoreCache.Indicator
          root: ExtractedIndicators.IP
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: A context script for IP entities
      id: 9ba6d580-552b-4dd2-80b0-444a9b73f07d
      iscommand: false
      name: IP Reputation on New Indicators
      script: IPReputation
      type: regular
      version: -1
    taskid: 9ba6d580-552b-4dd2-80b0-444a9b73f07d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 612.5,
          "y": 865
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: DBotScoreCache.Expired
          operator: isEqualString
          right:
            value:
              simple: "true"
      label: "yes"
    id: "7"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fd2cfca4-28f9-40a2-8d3e-08ef555b5583
      iscommand: false
      name: Are there Expired Indicators?
      type: condition
      version: -1
    taskid: fd2cfca4-28f9-40a2-8d3e-08ef555b5583
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      indicatorsValues:
        complex:
          accessor: Indicator
          filters:
          - - left:
                iscontext: true
                value:
                  simple: DBotScoreCache.Expired
              operator: isEqualString
              right:
                value:
                  simple: "true"
          root: DBotScoreCache
      using-brand: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.enrich.indicators
      id: 30491e69-072c-428e-8f1e-35f6d448ea5a
      iscommand: true
      name: Enrich Expired Indicators
      script: Builtin|||enrichIndicators
      type: regular
      version: -1
    taskid: 30491e69-072c-428e-8f1e-35f6d448ea5a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 865
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 016e763c-1b01-44d1-874b-c832e1bc499b
      iscommand: false
      name: Fin
      type: title
      version: -1
    taskid: 016e763c-1b01-44d1-874b-c832e1bc499b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1040
        }
      }
  "10":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ExtractedIndicators.IP
          operator: notIn
          right:
            iscontext: true
            value:
              simple: DBotScoreCache.Indicator
      label: "yes"
    id: "10"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ddadace8-081b-4711-82a9-1ed0f0be6299
      iscommand: false
      name: Are there indicators not in the DBotScore cache?
      type: condition
      version: -1
    taskid: ddadace8-081b-4711-82a9-1ed0f0be6299
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 690
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1055,
        "width": 942.5,
        "x": 50,
        "y": 50
      }
    }
  }
